os: linux

dist: xenial

language: java

jdk:
    - openjdk11

env:
    - GRAALVM_VERSION="20.0.0" GRAALVM_JAVA_VERSION="11" GRAALPHP_BUILD_NATIVE="false"

install:
    - GRAAL_VM="https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java11-linux-amd64-20.0.0.tar.gz"
    - curl -LJ $GRAAL_VM --output graalvm.tar.gz
    - tar -xzf graalvm.tar.gz
    - JAVA_HOME=$(pwd)/graalvm-ce-java11-20.0.0
    - echo $JAVA_HOME
    - export JAVA_HOME
    - $JAVA_HOME/bin/gu install native-image

script:
  - ./generate_parser
  - mvn package
  # graal native tests
#  - ./graalphp ./graalphp-language/tests/Add.sl
#  - if [[ "GRAALPHP_BUILD_NATIVE" == "true" ]]; then  ./native/graalphp-native ./graalphp-language/tests/Add.sl; fi;
#  - if [[ "GRAALPHP_BUILD_NATIVE" == "true" ]]; then  $JAVA_HOME/bin/gu install -L ./graalphp-component/graalphp-component.jar; fi;
#  - if [[ "GRAALPHP_BUILD_NATIVE" == "true" ]]; then  $JAVA_HOME/bin/graalphp ./graalphp-language/tests/Add.sl; fi;
#  - if [[ "GRAALPHP_BUILD_NATIVE" == "true" ]]; then  $JAVA_HOME/bin/graalphp-native ./graalphp-language/tests/Add.sl; fi;
#  - if [[ "GRAALPHP_BUILD_NATIVE" == "true" ]]; then  $JAVA_HOME/bin/polyglot --jvm --language graalphp --file graalphp-language/tests/Add.sl; fi;
#  - if [[ "GRAALPHP_BUILD_NATIVE" == "true" ]]; then  $JAVA_HOME/bin/gu remove com.oracle.truffle.sl; fi;
  # test scripts
  - shellcheck graalphp;
  # - (find . -name '*.sh' | grep -v graalvm | xargs shellcheck);
  - bash <(curl -s https://codecov.io/bash)
