os:
    - linux

language: java

jdk:
    - openjdk11

env:
    - GRAALVM_VERSION="20.0.0" GRAALVM_JAVA_VERSION="11" GRAALPHP_BUILD_NATIVE="false"

install:
    - |
      GRAAL_VM="https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java11-linux-aarch64-20.0.0.tar.gz"
      curl -LJ $GRAAL_VM --output graalvm.tar.gz
      tar -xzf graalvm.tar.gz
      JAVA_HOME="$(pwd)/graalvm-ce-java11-20.0.0"
      export JAVA_HOME

script:
- mvn package
- ./graalphp ./graalphp-language/tests/Add.sl
- ./native/graalphp-native ./graalphp-language/tests/Add.sl;
- "$JAVA_HOME/bin/gu" install -L ./graalphp-component/graalphp-component.jar;
- "$JAVA_HOME/bin/graalphp" ./graalphp-language/tests/Add.sl;
- "$JAVA_HOME/bin/graalphp-native" ./graalphp-language/tests/Add.sl;
- "$JAVA_HOME/bin/polyglot" --jvm --language graalphp --file graalphp-language/tests/Add.sl;
- "$JAVA_HOME/bin/gu" remove com.oracle.truffle.sl;
- ./generate_parser
- mvn package
- ./graalphp graalphp-language/tests/Add.sl
- shellcheck graalphp;
- (find . -name '*.sh' | grep -v graalvm | xargs shellcheck);
