os: linux

dist: xenial

language: java

jdk:
  - openjdk11

env:
  - GRAALVM_VERSION="20.0.0" GRAALVM_JAVA_VERSION="11" GRAALPHP_BUILD_NATIVE="false" TEST="./graalphp-language/tests/dummy.php"

install:
  - GRAAL_VM="https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java11-linux-amd64-20.0.0.tar.gz"
  - curl -LJ $GRAAL_VM --output graalvm.tar.gz
  - tar -xzf graalvm.tar.gz
  - JAVA_HOME=$(pwd)/graalvm-ce-java11-20.0.0
  - echo $JAVA_HOME
  - export JAVA_HOME
  - $JAVA_HOME/bin/gu install native-image
script:
  - mvn package
  - ./graalphp $TEST
  - if [[ "GRAALPHP_BUILD_NATIVE" == "true" ]]; then  ./graalphp-native/graalphp-native $TEST; fi;
  - if [[ "GRAALPHP_BUILD_NATIVE" == "true" ]]; then  $JAVA_HOME/bin/gu install -L ./graalphp-component/graalphp-component.jar; fi;
  - if [[ "GRAALPHP_BUILD_NATIVE" == "true" ]]; then  $JAVA_HOME/bin/graalphp $TEST; fi;
  - if [[ "GRAALPHP_BUILD_NATIVE" == "true" ]]; then  $JAVA_HOME/bin/graalphp-native $TEST;  fi;
  - if [[ "GRAALPHP_BUILD_NATIVE" == "true" ]]; then  $JAVA_HOME/bin/polyglot --jvm --language graalphp --file $TEST; fi;
  - if [[ "GRAALPHP_BUILD_NATIVE" == "true" ]]; then  $JAVA_HOME/bin/gu remove org.graalphp; fi;
